Resolve #169, Alert Dialog When Deleting Last Time Table
sparcs-kaist/otl-app pull request #170
Opened 2024-03-18 10:41 UTC by RGLie

## Decription
Timetable Tab에서 마지막 Timetable을 삭제하는 버튼을 클릭시 삭제할 수 없다는 알림 다이얼로그 나오게 추가 하였습니다.  
'내 시간표'는 삭제할 수 없도록 삭제 버튼을 삭제하였습니다.

2024-03-20 04:40 UTC, sboh1214 commented on lib/pages/timetable_page.dart
> +              // onTapPos: () {}
이거 주석으로 남겨놓으신 이유가 있나요?

2024-03-20 04:44 UTC, sboh1214 commented on lib/widgets/timetable_tabs.dart
> +      // bool canDelete = widget.length > 2 && i != 0;
삭제하셔도 좋을 것 같아요 :)

2024-03-20 04:45 UTC, sboh1214 commented on lib/widgets/timetable_tabs.dart
> +                // disabled: !canDelete,
삭제 가능~!

2024-03-20 04:46 UTC, sboh1214 requested changes
위 사항들 한번 확인해 주시면 좋을 것 같습니다 :)

2024-03-20 14:30 UTC, RGLie commented on lib/widgets/timetable_tabs.dart
> +                // disabled: !canDelete,
작업하다 안지운것 같습니다. 삭제 했습니다!

2024-03-22 14:10 UTC, sboh1214 approved these changes
![image](https://github.com/sparcs-kaist/otl-app/assets/30364442/3ea210b5-2224-4fa4-95d8-b7716f375d88)

2024-03-22 14:11 UTC, merged