feat: add liked reviews, hall of fame, modify my reviews, latest reviews
sparcs-kaist/otl-app pull request #87
Opened 2023-05-09 14:38 UTC by hoosong0235

2023-05-15 16:07 UTC, sboh1214 requested changes
수고하셨습니다~!

2023-05-15 16:07 UTC, sboh1214 commented on lib/pages/liked_review_page.dart
> +    print('build');
중요한 로그라면 내용을 추가해 주시고, 아니라면 삭제해 주세요~

2023-05-15 16:07 UTC, sboh1214 commented on lib/pages/my_review_page.dart
> +    print('build');
마찬가지입니다 :)

2023-05-15 16:07 UTC, sboh1214 commented on lib/pages/my_review_page.dart
> +            end: DateTime.now()))
beginning과 end를 DateTime.now()로 처리하신 이유가 있나요?

2023-05-15 16:07 UTC, sboh1214 commented on lib/pages/review_page.dart
> +  int _selectedSemester = 3;
현재 시점으로 고정해도 될까요?

2023-05-15 16:07 UTC, sboh1214 commented on lib/pages/review_page.dart
> +              // ),
꼭 필요한 내용이 아니라면 주석을 삭제해도 좋을 것 같습니다

2023-05-15 16:07 UTC, sboh1214 commented on lib/pages/review_page.dart
> +                    _selectedYear = (2022.5 - index / 2).toInt();
2022.5 가 고정되어 있어요

2023-05-15 18:32 UTC, hoosong0235 commented on lib/pages/my_review_page.dart
> +            end: DateTime.now()))
아뇨 따로 이유는 없습니다! 기존에 구현되어 있던 방식을 유지했습니다.

2023-05-17 20:29 UTC, sboh1214 requested changes
명예의 전당에서 표출되는 학기를 otlplus-web에서는 어떻게 계산하고 있는지 확인했습니다.
꼼꼼하게 리뷰 요청해 주셔서 감사합니다 :)

2023-05-17 20:29 UTC, sboh1214 commented on lib/pages/review_page.dart
> +    int length = (_initialYear - 2013) * 2 + (_initialSemester == 1 ? 1 : 2);
otlplus-web에서는 아래와 같이 성적게시일을 기준으로 명예의 전당 학기 개수를 산출하고 있습니다.


```javascript
const now = new Date();
    return semesters.filter(
      (s) => s.year >= 2013 && now - new Date(s.gradePosting) > 30 * 24 * 60 * 60 * 1000,
    );
```

2023-05-17 20:29 UTC, sboh1214 commented on lib/pages/review_page.dart
> +  int _initialSemester = DateTime.now().month < 7 ? 3 : 1;
otlplus-web에서는 2013년 봄부터 배열되어 있기 때문에 아래와 같이 배열의 끝을 initial semester로 지정하고 있습니다.

```javascript
_setStartSemester = () => {
    const targetSemesters = this._getTargetSemesters();
    this.setState({
      selectedSemester: targetSemesters[targetSemesters.length - 1],
    });
  };
```

https://github.com/sparcs-kaist/otlplus-web/blob/f20712ee700cfae59c73d6238468afd5d9cd8aae/src/components/sections/write-reviews/reviewsright/RankedReviewsSubSection.js#L92

2023-05-17 20:29 UTC, sboh1214 commented on lib/pages/review_page.dart
> +    int length = (_initialYear - 2013) * 2 + (_initialSemester == 1 ? 1 : 2);
https://github.com/sparcs-kaist/otlplus-web/blob/f20712ee700cfae59c73d6238468afd5d9cd8aae/src/components/sections/write-reviews/reviewsright/RankedReviewsSubSection.js#L76

2023-06-29 16:40 UTC, merged